### ISSUE TITLE
Analyze should directly show first iteration results

### ISSUE THREAD

**Issue by alicakmak** [MuhammedHasan/metabol#10]
Currently, once a user enters some metabolite measurements and clicks on Analyze, it does not immediately show the results of the first iteration. The user is required to make one more click on the next page to have the first iteration results. We should eliminate that extra click, and let the user see the first iteration results after providing metabolite observations and clicking on Analyze button.

**Comment by MuhammedHasan** [comment]
Bug fix ae18fb7f97e338c15271e7831d1910454f70b1ac
