### ISSUE TITLE
On "Analyze" page, correct a button label and add a new option

### ISSUE THREAD

**Issue by alicakmak** [MuhammedHasan/metabol#11]
-- Rename "Add Manual" label to "Manually Add Metabolite Changes".

-- Add one more option "Use the Sample Metabolite Change List"

 "Upload File" OR "Manually Add Metabolite Changes" OR "Use the Sample Metabolite Change List"

**Comment by MuhammedHasan** [comment]
Feature added efa3e34d6d0d14d9dbfc3afee4910abc352a9564
