### ISSUE TITLE
User Profile Information Empty

### ISSUE THREAD

**Issue by alicakmak** [MuhammedHasan/metabol#13]
After a user logs in, s/he is redirected to his/her profile information page where s/he can edit the current profile information. Presently, all the profile information fields are empty, although they were entered during signup.

**Comment by MuhammedHasan** [comment]
Also we should divide current form into two form ones for user information other for password.

**Comment by MuhammedHasan** [comment]
8a9e260861a6d336b71b63d20e0ebfac1a9437c3
