### ISSUE TITLE
Incorporate flux information into the visualization

### ISSUE THREAD

**Issue by alicakmak** [MuhammedHasan/metabol#21]
The thickness and color of edges that connect reactions to their metabolites should be set according to the flux computed for that reaction. Higher flux should lead to thicker edger. The coloring of edges with non-zero flux should be different than the rest. The edges with zero flux may be grey and thin, and the edges with some flux may be light orange (or blue or green) with thickness set according to the flux.

**Comment by alicakmak** [comment]
If there is space, the flux information may be written in paranthesis next to the reaction name. If the number is less than zero, we should allow at most two digits after the point. Otherwise, we should allow only one digit after the point. That is, we should do rounding to reduce the required space.

**Comment by MuhammedHasan** [comment]
815ab2999c86315bebc58bc2f68f9dc28b431912

**Comment by alicakmak** [comment]
Let's add the flux value as specified in my above post, as well.

**Comment by MuhammedHasan** [comment]
749c695cd778104588db0e32792a902ed3ca7a9c
