### ISSUE TITLE
New save feature

### ISSUE THREAD

**Issue by alicakmak** [MuhammedHasan/metabol#22]
1. We will modify the functionality of the current save button that is located at the top-left corner of the visualization area as follows:

-- When this button is clicked, it will open up save file dialog to let use download the current visualization as an image file.

Let's also change the image on this button. The "floppy disk" is not clearly visible. Let's use a clearer floppy disk image.
1. Let's add a new Save button (outside of visualization area) possibly above the visualization pane with label "Save the Current Analysis". When clicked, it should popup a small window asking for a name. In this popup, by default, the name field may be prefilled with date and time of the saving, e.g., "My Analysis - Aug. 12, 2016 - 08:46". We may still keep the analysis name field on the previous screen where the user uploads measurements. The default value on that screen should be also similar to the above one. If the user typed something in the name field on the first screen, then the popup box in the next screen should be prefilled with that value rather than the default value.
2. Please relabel the title of the visualization box as "Metabolic subnetwork visualization - Iteration X".

**Comment by MuhammedHasan** [comment]
Only save as png feature.
