### ISSUE TITLE
Miscoloring of metabolites for a reaction

### ISSUE THREAD

**Issue by alicakmak** [MuhammedHasan/metabol#24]
All metabolites regardless of its role are colored green. Products should be green and substrates should be red.

http://muhammedhasan.github.io/metabol/reaction/G6PDH2c

**Comment by alicakmak** [comment]
Similar problem in metabolite detail page: 

Producers should be green, consumers should be red. If a reaction is reversible it may be colored as orange, as it may be a consumer or producer depending on the setting.

http://muhammedhasan.github.io/metabol/metabolite/6pgl[c]

**Comment by MuhammedHasan** [comment]
FIxed
