### ISSUE TITLE
New Feature: Browse by Subsystems

### ISSUE THREAD

**Issue by alicakmak** [MuhammedHasan/metabol#28]
Add a screen which will list subsystems (with the number of reactions in it in parenthesis next to the subsystem name) on the left, and clicking on a subsystem will list all reactions included in that subsystem on the right. Clicking on a reaction will go to reaction details. Also in subsystem details, we should see the connected subsystems in a table before the reaction list. In this table, for each connected subsystem, we should also provide the metabolites that provide the connections to the other subsystem, and for each connecting metabolite we should list the reactions in the current subsystem in which the connecting metabolite participates in any role. 

This screen will be accessed by clicking on a new menu button, "Browse".

**Comment by alicakmak** [comment]
This screen will be accessed by clicking on a new menu button, "Browse".

**Comment by MuhammedHasan** [comment]
8a9e260861a6d336b71b63d20e0ebfac1a9437c3
