### ISSUE TITLE
Visualization Feature: Subsystem View

### ISSUE THREAD

**Issue by alicakmak** [MuhammedHasan/metabol#32]
Add a widget into visualization toolbar that will allow to switch between "Reaction View" and "Subsystem View" of the visualized graph. Reaction View is the currently used default view of the graph. Subsystem View will summarize the network at subsystem level. More specifically, in subsystem view, nodes will be subsystems. All the reaction and metabolite nodes that belong to a subsystem will be collapsed down into a single node (rectangle) which represents the subsystem. If a metabolite is shared by multiple subsystems we should draw it as a separate metabolite node (circle) and there should be connection between such metabolite nodes and connected subsystem nodes. Double clicking on a susbsytem node may expand that subsystem, and add its reactions and metabolites into the graph. Double clicking on a reaction may collapse down the subsystem that it belongs to. The most recently collapsed down subsystem may have a different color to differentiate it from the others.

**Comment by MuhammedHasan** [comment]
4c9d37351d3485c2129467a30a8e3dded2cd0151

**Comment by MuhammedHasan** [comment]
Implemented for metabolite although buggy
