### ISSUE TITLE
New Analysis Result Page 

### ISSUE THREAD

**Issue by alicakmak** [MuhammedHasan/metabol#33]
The drawings are attached. The results will come from the algorithm that Mohamed is implementing.
![p1](https://cloud.githubusercontent.com/assets/5516962/18005117/bde31794-6ba0-11e6-862d-1cecf5b7673b.jpg)
![p2](https://cloud.githubusercontent.com/assets/5516962/18005122/c57f64da-6ba0-11e6-82cd-da3079aff2b4.jpg)
![overview](https://cloud.githubusercontent.com/assets/5516962/18005125/ca9bc2ec-6ba0-11e6-8d7d-6b9130a6e90d.jpg)

**Comment by MuhammedHasan** [comment]
c1579b45e449aedfc1826d6a4de88bc6a2729ef2
