### ISSUE TITLE
Disconnected graph in subsystem view

### ISSUE THREAD

**Issue by alicakmak** [MuhammedHasan/metabol#35]
Reaction view: connected graph
Subsystem view: disconnected graph

http://muhammedhasan.github.io/metabol/metabolite/fum_c

**Comment by MuhammedHasan** [comment]
It is connected either reaction view or subsystem view. Can you check with clean browser cache.

**Comment by alicakmak** [comment]
The screenshot is attached. There is some sort of caching, but I could not understand where it is resulting from.

![image](https://cloud.githubusercontent.com/assets/5516962/19312228/2b60d3c4-909a-11e6-9a2a-aede1e078fd2.png)

**Comment by MuhammedHasan** [comment]
I am really confused. I checked link at night and i saw same bug and fixed it.

dada075a35f5cc07787a189a29837d48c0a97d99

**Comment by alicakmak** [comment]
Muhammed,
Can you please describe what the problem was, and how you fixed it?

**Comment by MuhammedHasan** [comment]
The bug is in my algorithm. I have only connected border metabolite with its child reaction's subsystem but I also should connect this metabolite its parent's subsystem.

**Comment by alicakmak** [comment]
Ok, but how do we explain that it was showing a non-deterministic behavior?

**Comment by MuhammedHasan** [comment]
I do not know. I am looking for it.
