### ISSUE TITLE
Loading message needed for whatever pages required

### ISSUE THREAD

**Issue by alicakmak** [MuhammedHasan/metabol#9]
For some pages, the loading of the content takes some time. We need to investigate why it is taking that much time, and whether that may be improved by possibly re-writing the SQL queries and/or creating new indexes on the database. That is a separate issue but until then, we should add "Loading" message or animation on several pages. The ones that immediately need this enhancement are:

-- Metabolite detail page (visualization and connected reactions part)
-- Reaction detail page (visualization and connected reactions part)
-- Analyze page between iterations

**Comment by MuhammedHasan** [comment]
66e6087ea82f2896c089dcc784a289677fb82bf6

**Comment by MuhammedHasan** [comment]
1b86298c1f5f5a4ae7d38143fbd6d92cc2c38b95

**Comment by MuhammedHasan** [comment]
Feature added
